# autogenerated by txs
#include:expl3
#include:l3str
\__ctex_tmp:w#S
\ctex_get_macro_meaning:NTF#S
\ctex_parse_name:NNx#S
\msg extra text > ctex/patch-failure#S
\msg text > ctex/patch-failure#S
\tl_rescan:no#S
expl3.sty#S
